version: 1.0.{build}

image: Ubuntu

stack: node 14

branches:
  only:
    - master

cache: node_modules

install:
- npm install

build: off

test_script:
- npm test & npm run lint
